#!/bin/bash

# Tworzenie katalogu /usr/share/applications, jeśli go nie ma
mkdir -p /usr/share/applications

# Nadanie uprawnień do aplikacji
chmod +x /usr/local/bin/brightness-app

# Kopiowanie pliku .desktop do katalogu aplikacji
cp /usr/local/bin/brightness-app.desktop /usr/share/applications/

# Odświeżenie menu aplikacji
update-desktop-database /usr/share/applications/
gtk-update-icon-cache /usr/share/icons/hicolor/

# Komunikat po zakończeniu instalacji
echo "Brightness App została zainstalowana pomyślnie!"

